paths:
  /books:
    post:
      tags:
        - Book
      summary: 책 생성
      parameters:
        - in: header 
          name: authorization
          required: true
          schema:
            properties:
              authorization:
                type: string
                description: accessToken
                example: Bearer 
        - in: header
          name: refresh
          required: true
          schema:
            properties:
              refresh:
                type: string
                description: refreshToken
        - in: body
          name: create book
          required: true
          schema:
            properties:
              title:
                type: varchar(50)
                description: 책 제목
                example: 책 제목
              intro:
                type: varchar(50)
                description: 책 소개
                example: 책 소개
              category:
                type: varchar(100)
                description: 책 장르
                example: 책 장르
              bookContents:
                type: object
                description: 목차 정보
                example: [ {
                    "index": 1,
                    "title": "목차 제목1",
                    "context": "목차의 내용1"
                  }, {
                    "index": 2,
                    "title": "목차 제목2",
                    "context": "목차의 내용2"
                  }]
      responses:
        '200':
          description: 책 생성 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 200
              message:
                type: string
                example: "success!"
              result:
                type: object
                example: {
                  "id": 33,
                  "title": "책 제목 예시2",
                  "intro": "책 소개 예시2",
                  "category": "일상",
                  "user_id": 1,
                  "storage": false,
                  "like": false,
                  "contents": [{
                        "id": 52,
                        "title": "목차 제목1",
                        "content": "목차의 내용1",
                        "create_at": "2024-02-05T07:41:01.000Z",
                        "index": 1,
                        "book_id": 33
                    },{
                        "id": 53,
                        "title": "목차 제목2",
                        "content": "목차의 내용2",
                        "create_at": "2024-02-05T07:41:01.000Z",
                        "index": 2,
                        "book_id": 33
                    }]
                  }

        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

  /books/{bookId}:
    get:
      tags:
        - Book
      summary: 책 상세조회
      parameters:
        - in: path
          name: bookId
          required: true
          schema:
            properties:
              bookId:
                type: integer
                description: 책 일련번호
                example: 31
        - in: header 
          name: authorization
          required: true
          schema:
            properties:
              authorization:
                type: string
                description: accessToken
                example: Bearer 
        - in: header
          name: refresh
          required: true
          schema:
            properties:
              refresh:
                type: string
                description: refreshToken
      responses:
        '200':
          description: 책 조회 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 200
              message:
                type: string
                example: "success!"
              result:
                type: object
                example: {
                  "id": 33,
                  "title": "책 제목 예시2",
                  "intro": "책 소개 예시2",
                  "category": "일상",
                  "user_id": 1 ,
                  "storage": false,
                  "like": false,
                  "contents": [{
                        "id": 52,
                        "title": "목차 제목1",
                        "content": "목차의 내용1",
                        "create_at": "2024-02-05T07:41:01.000Z",
                        "index": 1,
                        "book_id": 33
                    },{
                        "id": 53,
                        "title": "목차 제목2",
                        "content": "목차의 내용2",
                        "create_at": "2024-02-05T07:41:01.000Z",
                        "index": 2,
                        "book_id": 33
                    }]
                  }

        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

    patch:
      tags:
        - Book
      summary: 책 수정
      parameters:
        - in: header 
          name: authorization
          required: true
          schema:
            properties:
              authorization:
                type: string
                description: accessToken
                example: Bearer 
        - in: header
          name: refresh
          required: true
          schema:
            properties:
              refresh:
                type: string
                description: refreshToken
        - in: path
          name: bookId
          required: true
          schema:
            properties:
              bookId:
                type: integer
                description: 책 일련번호
                example: 1
        - in: body
          name: update book body
          required: true
          schema:
            properties:
              title:
                type: varchar(50)
                description: 책 제목
                example: 책 제목
              intro:
                type: varchar(50)
                description: 책 소개
                example: 책 소개
              category:
                type: varchar(100)
                description: 책 장르
                example: 책 장르
              bookContents:
                type: object
                description: 목차 정보
                example: 
                  - index: 1
                    title: "목차 제목1"
                    context: "목차의 내용1"
                  - index: 2
                    title: "목차 제목2"
                    context: "목차의 내용2"
      responses:
        '200':
          description: 책 조회 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 200
              message:
                type: string
                example: "success!"
              result:
                type: object
                example:
                  id: 33
                  title: "책 제목 예시2"
                  intro: "책 소개 예시2"
                  category: "일상"
                  user_id: 1,
                  storage: false,
                  like: false,
                  contents: 
                    - id: 52
                      title: "목차 제목1"
                      content: "목차의 내용1"
                      create_at: "2024-02-05T07:41:01.000Z"
                      index: 1
                      book_id: 33
                    - id: 53
                      title: "목차 제목2"
                      content: "목차의 내용2"
                      create_at: "2024-02-05T07:41:01.000Z"
                      index: 2
                      book_id: 33

        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

    delete:
      tags:
        - Book
      summary: 책 삭제
      parameters:
        - in: path
          name: bookId
          required: true
          schema:
            properties:
              bookId:
                type: integer
                description: 책 일련번호
                example: 1
        - in: header 
          name: authorization
          required: true
          schema:
            properties:
              authorization:
                type: string
                description: accessToken
                example: Bearer 
        - in: header
          name: refresh
          required: true
          schema:
            properties:
              refresh:
                type: string
                description: refreshToken
      responses:
        '200':
          description: 책 조회 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 200
              message:
                type: string
                example: "success!"
              result:
                type: object
                example: {
                  "deletedBook": 1,
                  "deletedBookContent": 2,
                  "deletedBookStorage": 0,
                  "deletedBookLike": 0
                }

        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

  /books/img:
    post:
      summary: Uploads a file.
      consumes:
        - multipart/form-data  # 문서 타입 지정
      parameters:
        - in: query
          name: directory
          type: string
        - in: formData
          name: image
          type: file
          description: 파일 업로드
      responses:
        '200':
          description: 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 200
              message:
                type: string
                example: "success!"
              result:
                type: object

        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.


