paths:
  /login:
    post:
      tags:
        - User
      summary: 로그인
      parameters:
        - name: signup
          in: body
          required: true
          schema:
            properties:
              email:
                type: varchar(50)
                description: 유저 이메일
                example: jade@example.com
              pw:
                type: varchar(100)
                description: 유져 비밀번호
                example: kongji0717!
              auto:
                type: boolean
                description: 자동 로그인
                example: True
      responses:
        '200':
          description: 회원 가입 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "nickname": "Jade",
                }

        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.