paths:
  /mypage/image/{userId}:
    patch:
      tags:
        - User
      summary: 프로필 이미지 변경
      parameters:
        - name: userId
          in: path
          required: true
          description: 사용자 ID
          schema:
            properties:
              usrId:
                type: string
                example: "14"
        - name: changeimage
          in: body
          required: true
          schema:
            type: object
            properties:
              img:
                type: string
                description: 사용자 프로픽 사진
                example:
      responses:
        '200':
          description: 닉네임 변경이 완료되었습니다!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "success!"
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON001
                  message:
                    type: string

