paths:
  /mypage/nickname/{userId}:
    patch:
      tags:
        - User
      summary: 사용자 닉네임 변경
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            properties:
              id:
                type: string
                example: "14"
        - name: changenick
          in: body
          required: true
          schema:
            type: object
            properties:
              changenick:
                type: varchar(50)
                description: 사용자 닉네임
                example: 콩지
      responses:
        '200':
          description: 닉네임 변경이 완료되었습니다!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "success!"
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON001
                  message:
                    type: string
