paths:
  /questions:
    get:
      tags:
        - Todayquestion
      summary: 오늘의 질문
      responses:
        '2000':
          description: 질문 제공 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 2000
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  question_id: 3,
                  content: '제일 좋아하는 영화는 무엇인가요?'
                }
    post:
      tags:
        - Todayquestion
      summary: 답변 작성
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: 사용자 JWT 토큰
          example: Bearer your-jwt-token 
        - name: Refresh
          in: header
          required: false
          type: string
          description: 사용자 Refresh 토큰
          example: your-refresh-token 
        - name: answer
          in: body
          required: true
          schema:
              properties:
                content:
                  type: string
                  description: 내용
                  example: 저는 딸기를 가장 좋아해요. 싱싱한 딸기를 살 수 있다는 건 포근하고 차가운 겨울이 다가온다는 의미니까요.
              required:
                - content
      responses:
        '2000':
          description: 답변 등록 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 2000
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  answer_id: 12,
                  content: 저는 딸기를 가장 좋아해요. 싱싱한 딸기를 살 수 있다는 건 포근하고 차가운 겨울이 다가온다는 의미니까요.
                }

  /questions/{question_id}:
    get:
      tags:
        - Todayquestion
      summary: 답변 조회
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: 사용자 JWT 토큰
          example: Bearer your-jwt-token 
        - name: Refresh
          in: header
          required: false
          type: string
          description: 사용자 Refresh 토큰
          example: your-refresh-token 
        - name: question_id
          in: path
          required: true
          description: 질문 ID
          schema:
            type: integer
      responses:
        '2000':
          description: 글 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 2000
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "question": "제일 좋아하는 과일은 무엇인가요?",
                  "answer": "저는 딸기를 가장 좋아해요. 싱싱한 딸기를 살 수 있다는 건 포근하고 차가운 겨울이 다가온다는 의미니까요."
                }